/**
 * Garment data types.
 *
 * A garment is a clothing item that a tenant uploads for virtual try-on.
 * Unlike user images, garments are tenant-owned catalog assets — they
 * persist as long as the tenant wants them (no forced TTL).
 *
 * This module defines the data model and enums for garment types.
 * No processing logic here — types only.
 */

// ─── Garment Type Enums ──────────────────────────────────────────────────────

/**
 * High-level garment category.
 * Determines which body region the try-on engine targets.
 */
export const GARMENT_TYPES = [
  "TOP",
  "BOTTOM",
  "DRESS",
  "OUTERWEAR",
  "ACCESSORY",
] as const;

export type GarmentType = (typeof GARMENT_TYPES)[number];

/**
 * Fine-grained garment category for filtering and UI display.
 * Each maps to a parent GarmentType.
 */
export const GARMENT_CATEGORIES = {
  // TOP
  T_SHIRT: "TOP",
  SHIRT: "TOP",
  BLOUSE: "TOP",
  SWEATER: "TOP",
  HOODIE: "TOP",
  TANK_TOP: "TOP",
  POLO: "TOP",

  // BOTTOM
  JEANS: "BOTTOM",
  TROUSERS: "BOTTOM",
  SHORTS: "BOTTOM",
  SKIRT: "BOTTOM",
  LEGGINGS: "BOTTOM",

  // DRESS
  CASUAL_DRESS: "DRESS",
  FORMAL_DRESS: "DRESS",
  MAXI_DRESS: "DRESS",

  // OUTERWEAR
  JACKET: "OUTERWEAR",
  COAT: "OUTERWEAR",
  BLAZER: "OUTERWEAR",
  VEST: "OUTERWEAR",

  // ACCESSORY
  SCARF: "ACCESSORY",
  HAT: "ACCESSORY",
  BAG: "ACCESSORY",
} as const satisfies Record<string, GarmentType>;

export type GarmentCategory = keyof typeof GARMENT_CATEGORIES;

// ─── Garment Entity ──────────────────────────────────────────────────────────

export interface Garment {
  /** Unique garment identifier. */
  id: string;
  /** Owning tenant. */
  tenantId: string;
  /** Human-readable name (e.g. "Blue Denim Jacket"). */
  name: string;
  /** High-level type. */
  type: GarmentType;
  /** Fine-grained category. */
  category: GarmentCategory;
  /** URL of the garment product image. */
  imageUrl: string;
  /**
   * URL of the garment mask image (alpha channel showing garment outline).
   * Optional — can be auto-generated by AI in a future phase.
   */
  maskUrl?: string;
  /** Arbitrary key-value attributes for extensibility (color, size, brand, etc.). */
  attributes: Record<string, string>;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** ISO 8601 last-updated timestamp. */
  updatedAt: string;
}

// ─── POST /garment ───────────────────────────────────────────────────────────

export interface CreateGarmentRequest {
  name: string;
  type: GarmentType;
  category: GarmentCategory;
  imageUrl: string;
  maskUrl?: string;
  attributes?: Record<string, string>;
}

export interface CreateGarmentResult {
  id: string;
  garment: Garment;
}
